# Change to your own name
site_name: Nirmalya Brahma
# Change to your own site
site_url: https://nirmalyabrahma.github.io/nbrahma/ # must have the trailing slash
site_author: nirmalya.brahma@mail.mcgill.ca
site_description: Research site for Nirmalya Brahma 
copyright: > # should remain a link to the original theme
  <p>Copyright &copy; 2025 Nirmalya Brahma  — All Rights Reserved.</p>
 


# <a href="https://github.com/vuquangtrong/mkdocs-material-blog">Blog Theme</a> /
# <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>


theme:
    name: material
    custom_dir: overrides
    icon:
      logo: material/atom-variant
    font: 
      text: Lexend
    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        # Color of the top bar
        primary: teal
        # Link highlight color
        accent : deep orange
        
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        accent : deep orange
        toggle:
          icon: material/weather-night
          name: Switch to light mode

    features:
    - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level sections are shown as tabs
    - navigation.tabs.sticky # tabs always show
    - navigation.sections # sections are rendered as groups in the sidebar
    - navigation.expand # all sections are expanded
    - navigation.indexes # link an index.md page to a section
    - navigation.top # show back-to-top button
    - toc.follow
    - toc.integrate # show table of contents to navigation panel
    # - navigation.footer
    - header.autohide
    - content.code.annotate 
    - content.code.copy

extra_javascript:
# for rendering latex
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# For describing the navigation panel
nav:
  - Home: index.md
  - Research: research/index.md
  - Contact: contact.md
  - CV: media/CV_Nirmalya.pdf

  

# Extensions that we want to use
markdown_extensions:
  - toc:
      title: On this page
      toc_depth: 4
  - attr_list   # For adding attributes such as right/left align to images
  - md_in_html  # Using Figures
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.arithmatex:
  #     inline_syntax: ["$", "$"]
  #     generic: true



# Additional plugins
plugins:
    - search
    - offline
    # - search.suggest
    # - search.highlight
    # - search.share
    # Using jupyter notebook  
    - mkdocs-jupyter:
          theme: default

extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://ca.linkedin.com/in/nirmalya-brahma-952b2712a
    - icon: custom/inspirehep
      link: https://inspirehep.net/authors/2664905?ui-citation-summary=true
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX