name: Deploy MkDocs site from main/doc

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'   # Trigger only when files in doc/ change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install MkDocs and Material theme
      - name: Install MkDocs and plugins
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      # Step 4: Build the site
      - name: Build MkDocs site
        run: mkdocs build --config-file mkdocs.yml --strict

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          user_name: 'GitHub Actions'
          user_email: 'actions@github.com'
